name: CI CodeFactory

on:
  push:
    branches: [ "main", "desenvolvimento" ]
  pull_request:
    branches: [ "main", "desenvolvimento" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Verificar arquivos
      run: ls -R
    - name: Simular Teste
      run: echo "Testes automatizados concluídos com sucesso!"
